### ISSUE TITLE
支付宝相关的jar包没看到呢

### ISSUE THREAD

**Issue by j0012799** [tanglei302wqy/tlmall-springboot#2]

**Comment by tanglei302wqy** [comment]
1. README.md有文档[下载链接](https://docs.open.alipay.com/54/103419/)，下载后把对应的jar文件放到resources/lib下并加入到本地依赖中
2. Geely视频的maven版本较低，maven3.1之后<compilerArguments>标签改成 <compilerArgs>标签，注意版本兼容问题
3. maven打包本地jar[参考](https://blog.csdn.net/csdn2193714269/article/details/78391274)，亲测可行:smile:
